---
- name: 'Add Microsoft DNF/YUM key'
  ansible.builtin.rpm_key:
    key: '{{ microsoft_repository__key_url }}'
    state: present

- name: 'Add Microsoft DNF/YUM repository'
  ansible.builtin.yum_repository:
    name: 'packages-microsoft-prod'
    description: 'Microsoft repository'
    baseurl: '{{ microsoft_repository__url }}'
    file: 'microsoft-prod'
    gpgcheck: true
    enabled: true

- name: 'Install DNF/YUM packages'
  ansible.builtin.package:
    name: '{{ microsoft_repository__packages }}'
    state: present
