---
- name: 'RedHat | Configure the Microsoft repository and install packages from it'
  become: true
  block:
    - name: 'RedHat | Ensure the dependencies are installed'
      ansible.builtin.package:
        name: 'yum-utils'
        state: 'present'

    - name: 'RedHat | Add the Microsoft repository'
      ansible.builtin.template:
        src: 'microsoft.repo.j2'
        dest: '/etc/yum.repos.d/packages-microsoft-com.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'RedHat | Install packages from the Microsoft repository'
      ansible.builtin.package:
        name: '{{ microsoft_repository_packages }}'
        state: 'present'
      when: not ansible_check_mode
