---
- name: 'Ensure dependencies are installed'
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: 'Add Microsoft APT key'
  ansible.builtin.apt_key:
    url: '{{ microsoft_repository_key_url }}'
    state: present

- name: 'Add Microsoft APT repository'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] {{ microsoft_repository_url }} {{ ansible_distribution_release }} main'
    filename: 'microsoft-prod'
    state: present

- name: 'Install APT packages'
  ansible.builtin.apt:
    name: '{{ microsoft_repository_packages }}'
    state: present
