---
- name: 'Configure APT repository and install packages'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: 'Add Microsoft APT key'
      ansible.builtin.apt_key:
        url: '{{ microsoft_repository_key_url }}'
        state: present
      when: not ansible_check_mode

    - name: 'Add Microsoft APT repository'
      ansible.builtin.template:
        src: 'microsoft.list.j2'
        dest: '/etc/apt/sources.list.d/packages-microsoft-com.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install APT packages'
      ansible.builtin.apt:
        name: '{{ microsoft_repository_packages }}'
        update_cache: true
        state: present
      when: not ansible_check_mode
