---
- name: 'Configure APT repository and install packages'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: 'Add Microsoft APT key'
      ansible.builtin.apt_key:
        url: '{{ microsoft_repository_key_url }}'
        state: present
      when: not ansible_check_mode

    - name: 'Add Microsoft APT repository'
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] {{ _microsoft_repository_url }} {{ ansible_distribution_release }} main'
        filename: '{{ microsoft_repository_dir.filename | default("packages-microsoft-com") }}'
        state: '{{ microsoft_repository_dir.state | default(omit) }}'
      vars:
        _microsoft_repository_url: >-
          {% if microsoft_repository_dir.type is defined and microsoft_repository_dir.type == 'alternate' -%}
            {{ microsoft_repository_mirror }}/repos/{{ microsoft_repository_dir.name }}
          {%- else -%}
            {{ _microsoft_repository_baseurl }}/{{ microsoft_repository_dir.name }}
          {%- endif %}
      loop: '{{ microsoft_repository_dirs_list }}'
      loop_control:
        loop_var: microsoft_repository_dir

    - name: 'Install APT packages'
      ansible.builtin.apt:
        name: '{{ microsoft_repository_packages }}'
        state: present
      when: not ansible_check_mode
