---
- name: 'Configure DNF/YUM repository and install packages'
  become: true
  block:
    - name: 'Add Microsoft DNF/YUM repository'
      ansible.builtin.template:
        src: 'microsoft.repo.j2'
        dest: '/etc/yum.repos.d/packages-microsoft-com.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install DNF/YUM packages'
      ansible.builtin.package:
        name: '{{ microsoft_repository_packages }}'
        state: present
      when: not ansible_check_mode
