---
- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include OS-specific tasks for install packages'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'
