---
- name: 'Include OS-specific Microsoft variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include OS-specific tasks to install Microsoft packages'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'
