---
- name: 'Converge'
  hosts: all
  roles:
    - role: antmelekhin.microsoft_repository
      microsoft_repository_dirs_list:
        - name: prod
        - name: azure-cli
          type: alternate
      microsoft_repository_packages:
        - powershell
        - azure-cli
