---
- name: 'Converge'
  hosts: all

  pre_tasks:
    - name: 'Update apt cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: antmelekhin.microsoft_repository
      microsoft_repository_dirs_list:
        - name: prod
          state: present
        - name: azure-cli
          type: alternate
      microsoft_repository_packages:
        - powershell
        - azure-cli
