---
- name: 'Converge'
  hosts: all
  roles:
    - role: antmelekhin.microsoft_repository
      microsoft_repository_additional_directories:
        - 'azure-cli'
      microsoft_repository_packages:
        - 'powershell'
        - 'azure-cli'
