---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check current Powershell version'
      ansible.builtin.command:
        cmd: pwsh --version
      changed_when: false
      register: _powershell_version_check

    - name: 'Check current AzureCLI version'
      ansible.builtin.shell:
        cmd: az --version | grep azure-cli
      changed_when: false
      register: _azurecli_version_check

    - name: 'Powershell version output'
      ansible.builtin.debug:
        var: _powershell_version_check.stdout

    - name: 'AzureCLI version output'
      ansible.builtin.debug:
        var: _azurecli_version_check.stdout
