---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check the current Powershell version'
      ansible.builtin.command:
        cmd: 'pwsh --version'
      changed_when: false
      register: __powershell_version_check

    - name: 'Check the current AzureCLI version'
      ansible.builtin.command:
        cmd: 'az version'
      changed_when: false
      register: __azurecli_version_check

    - name: 'Powershell version output'
      ansible.builtin.debug:
        msg: '{{ __powershell_version_check.stdout }}'

    - name: 'AzureCLI version output'
      ansible.builtin.debug:
        msg: '{{ __azurecli_version_check.stdout | from_json }}'
