---
name: 'Molecule'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Molecule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: 'debian-11'
          - distro: 'rockylinux-9'
          - distro: 'ubuntu-22.04'

    steps:
      - name: 'Checkout the codebase'
        uses: actions/checkout@v4

      - name: 'Testing an Ansible role with Molecule'
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          TAG: ${{ matrix.distro }}
